name: Build & Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo build --release

      - name: Package release folder
        shell: pwsh
        run: |
          Compress-Archive -Path target/release/* -DestinationPath tumbleweed.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: tumbleweed.zip
